export const NAV=[['home','index.html','首页','Home'],['downloads','downloads.html','软件下载','Downloads'],['speaker','speaker.html','讲师介绍','Speaker'],['concepts','concepts.html','概念图谱','Concepts'],['workflows','workflows.html','工作流','Workflows'],['tools','tools.html','工具实操','Hands-on']];
export const DOWNLOADS=[
{n:'01',name:'千问',en:'Qwen',desc:'手机录音纪要、电脑端语音输入与办公功能。',descEn:'Mobile meeting notes, desktop voice input, and office tools.',url:'https://www.qianwen.com/'},
{n:'02',name:'WorkBuddy',en:'WorkBuddy Desktop Agent',desc:'桌面办公智能体、技能扩展与微信远程控制。',descEn:'Desktop agent, reusable skills, and WeChat remote control.',url:'https://www.workbuddy.cn/'},
{n:'03',name:'Codex',en:'OpenAI Codex',desc:'用于课件、网站、代码、数据和文件型任务。',descEn:'For slides, websites, code, data, and file-based tasks.',url:'https://openai.com/codex/'},
{n:'04',name:'Claude',en:'Claude Desktop / Claude Code',desc:'适合代码项目、长上下文分析与代码动画。',descEn:'For coding projects, long-context analysis, and code-based animation.',url:'https://claude.com/download'},
{n:'05',name:'CC Switch',en:'Coding Configuration Switcher',desc:'管理并切换 Codex、Claude Code 等工具的模型配置。',descEn:'Manage and switch model configurations for Codex and Claude Code.',url:'https://ccswitch.io/zh/'},
{n:'06',name:'TokenOne',en:'Unified API Gateway',desc:'创建模型分组、生成 API 密钥并按实际用量付费。',descEn:'Create model groups, issue API keys, and pay by actual usage.',url:'http://gts.tokenone.work'}];
export const WORKFLOWS={
paper:{label:'论文写作',en:'Paper Writing',steps:[['明确问题','Define Question','研究问题、对象与边界','Question, scope, and boundaries'],['资料检索','Retrieve Sources','关键词、数据库与筛选标准','Keywords, databases, and screening'],['证据矩阵','Evidence Matrix','观点、方法、结论与来源','Claims, methods, findings, and sources'],['搭建结构','Build Structure','章节逻辑与论证链','Sections and argument chain'],['协同写作','Draft Together','逐段生成、引用回填','Draft section by section and restore citations'],['审校定稿','Review & Finalize','事实、引用、逻辑与AI痕迹','Facts, citations, logic, and AI traces']]},
ppt:{label:'PPT制作',en:'PPT Creation',steps:[['确定场景','Define Context','听众、时长、场地','Audience, time, and venue'],['提供模板','Provide Template','风格参考与优质样例','Style reference and strong examples'],['生成大纲','Create Outline','一页一观点','One idea per slide'],['准备素材','Prepare Assets','真实图片、数据与截图','Real images, data, and screenshots'],['制作课件','Build Slides','版式、讲稿与动画','Layout, notes, and motion'],['投影复核','Projector Review','字号、对比、节奏','Type size, contrast, and pacing']]},
video:{label:'视频制作',en:'Video Creation',steps:[['确定主题','Define Theme','对象、平台与时长','Audience, platform, and duration'],['脚本设计','Write Script','口播、画面与节奏','Voiceover, visuals, and pacing'],['分镜规划','Plan Shots','镜头、字幕与转场','Shots, captions, and transitions'],['素材生成','Generate Assets','图片、声音、代码动画','Images, audio, and code animation'],['合成剪辑','Edit & Compose','时间线、配乐与包装','Timeline, music, and packaging'],['发布复盘','Publish & Review','版权、数据与迭代','Rights, metrics, and iteration']]},
office:{label:'办公与比赛',en:'Office & Competition',steps:[['读取要求','Read Requirements','通知、指南与评分表','Notice, guide, and rubric'],['收集材料','Collect Materials','事实、附件与已有成果','Facts, files, and prior work'],['匹配模板','Match Template','标准格式与优秀样例','Required format and strong example'],['分工生成','Delegate to Agents','文稿、表格、PPT并行','Draft, spreadsheet, and slides in parallel'],['模拟评审','Simulate Review','三位评委打分与意见','Three-reviewer scoring and feedback'],['提交检查','Submission Check','一致性、真实性与格式','Consistency, accuracy, and format']]}}
